# INTRODUCCIÓN A PYTHON
## Tipos de variables

### *Numéricas*

In [1]:
A = 5
B = 2.1 + 7.3j  
C = 4.3e-2
E = 256.2

In [2]:
print(A,B,C)
print(type(A), type(B),type(C))

5 (2.1+7.3j) 0.043
<class 'int'> <class 'complex'> <class 'float'>


### *Cadenas de caracteres/string*

In [3]:
cad1 = 'Texto 1'
cad2 = "Texto 2"

In [4]:
print(cad1)
print(type(cad1))
print(cad2)
print(type(cad2))

Texto 1
<class 'str'>
Texto 2
<class 'str'>


In [5]:
cad3 = "Mi nombre es: \n\t  Hiram Isaí Torres Espinosa"
print(cad3)

Mi nombre es: 
	  Hiram Isaí Torres Espinosa


In [6]:
cad4 = """Texto
linea 1
linea 2
linea 3"""
print(cad4)

Texto
linea 1
linea 2
linea 3


### *Booleanas/Lógicas*

In [7]:
varT = True
varF = False

*True y False con mayúscula son palabras reservadas*

In [8]:
print(type(varT))
print(type(varF))

<class 'bool'>
<class 'bool'>


### *Estrucutas de datos: Listas, tuplas, dataframe, arrays*


#### *Listas*

Definimos una lista "l"

In [9]:
l = [1,"nombre", True, ["a",E]]
print(l)

[1, 'nombre', True, ['a', 256.2]]


In [10]:
print(type(l))

<class 'list'>


In [11]:
print(l[2])

True


#### *Arreglos*

In [12]:
import numpy as np

In [13]:
m1 = np.array([1,2,3])
m2 = np.array([(1,2,3),(4,5,6)])
m3 = np.array([(1,4,8),(5,2,1),(3,7,9)])

In [14]:
print("1D array")
print(m1)
print("3D array")
print(m3)
print("2D array")
print(m2)

1D array
[1 2 3]
3D array
[[1 4 8]
 [5 2 1]
 [3 7 9]]
2D array
[[1 2 3]
 [4 5 6]]


### Operadores

#### *Aritméticos*

In [15]:
# Suma
a = 20
b = 15
c = 5
d = 2.3

In [16]:
print(a+c) #Suma
print(a-b) #Resta
print(c**2) #Exponente
print(a/b) #División


25
5
25
1.3333333333333333


#### *Cadenas*

In [17]:
repetir = cad1*3  #Repetición
print(repetir)

Texto 1Texto 1Texto 1


In [18]:
concat = cad1+cad2  #Concatenación
print(concat)

Texto 1Texto 2


#### *Lógicos*

In [19]:
Oand = varT and varF  #AND
print(Oand)

False


In [20]:
Oor = varT or varF   #OR
print(Oor)

True


In [21]:
Onot1 = not varT   #NOT
Onot2 = not varF
print(Onot1)
print(Onot2)

False
True


#### *Relacionales*

In [22]:
V1 = 4
V2 = 5
V3 = 4

In [23]:
print(V1 == V2) #Iguales?
print(V1 == V3)

False
True


In [24]:
print(V1 != V2) #Diferentes?
print(V1 != V3)

True
False


In [25]:
print(V1 < V2) #Mayor o menor qué (<=)  (>=)
print(V1 > V2)

True
False


###  Sentencias condicionales


In [26]:
edad1 = 15
edad2 = 30
m_edad = 18

In [27]:
if edad2 >= m_edad:     #Condición simple
    print("Eres mayor de edad")# Indent es muy importante, no borrarlo
print("Esto se ejecuta siempre")

Eres mayor de edad
Esto se ejecuta siempre


In [28]:
edad = 50       #Condición anidada
if edad >= m_edad:
    print("Eres mayor de edad")# Indent es muy importante, no borrarlo
    if edad >= 60:
        print("Eres adulto de la tercera edad")

Eres mayor de edad


In [29]:
edad = 32

if edad >= 0 and edad < 18:     #Condición multiple
    print("Eresun niño")
elif edad >= 18 and edad < 27:
    print("Eres un joven")
elif edad >= 27 and edad < 60:
    print("Eres un adulto")



Eres un adulto


### Bucles

#### *While*

In [31]:
while True:   #Bucle infinito
    print("Hola")

Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola


KeyboardInterrupt: 

In [33]:
edad = 0
while edad <= 5:
    print("Tienes: " + str(edad))
    edad = edad+1

Tienes: 0
Tienes: 1
Tienes: 2
Tienes: 3
Tienes: 4
Tienes: 5


#### *For*

In [ ]:
lista = [ "Elemento 1","Elemento 2", "Elemento 3"]
for elem in lista:  #elem sólo es valido en el for y puede tener cualquier nombre
    print(elem)

Elemento 1
Elemento 2
Elemento 3


In [34]:
cadena = "Hiram"
for letra in cadena:
    print(letra)

H
i
r
a
m


Puede usarse para cualquier elemento de tipo secuencia

In [ ]:
import numpy as np

In [37]:
array1 = np.zeros(9)
array2 = np.array([(1,2),(9,8)])
for numero in array2, array1:
    print(numero)
    

[[1 2]
 [9 8]]
[0. 0. 0. 0. 0. 0. 0. 0. 0.]


### Funciones

In [ ]:
#Definición de la función
def nombre_funcion(num1,num2):  #Suma de dos números
    print(num1+num2)

In [ ]:
#Ejecutar la función
nombre_funcion(1,2)

3


In [38]:
def repetir(cad,var=2):
    print(cad*var)

In [41]:
repetir("Hiram ",3)

Hiram Hiram Hiram 
