1. Crear variables de tipo entero, punto flotante, string (cadena de texto) e imprimir sus tipos.
2. Crear una lista con múltiplos de 5, comenzando en 0 y hasta 100. Hint: ...
3. Usar los primeros 5 elementos de la lista anterior para imprimir esa cantidad de veces la letra 'A'. Ejemplo: 4. De [0, 5, 10, ...], para 5, sería imprimir 'AAAAA'.
5. Crear una matriz con números aleatorios usando numpy y trasponer la matriz.

In [5]:
a =5
b =2.65
c ="hola"
print (type(a))
print (type(b))
print (type(c))

<class 'int'>
<class 'float'>
<class 'str'>


In [4]:
lista = list(range(0,101,5))
print (lista)

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]


In [6]:
primeros_5 = lista[0:5]
print (primeros_5)


[0, 5, 10, 15, 20]


In [8]:
for valor in primeros_5:
    print (valor*"A")
    
    


AAAAA
AAAAAAAAAA
AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA


In [13]:
import numpy as np

A = np.random.random((3,3))
print (A)

[[0.61940231 0.21969051 0.74993031]
 [0.27532383 0.062626   0.50449268]
 [0.88168087 0.57197644 0.30733518]]


In [14]:
print (A)

[[0.61940231 0.21969051 0.74993031]
 [0.27532383 0.062626   0.50449268]
 [0.88168087 0.57197644 0.30733518]]


In [15]:
A.T

array([[0.61940231, 0.27532383, 0.88168087],
       [0.21969051, 0.062626  , 0.57197644],
       [0.74993031, 0.50449268, 0.30733518]])

In [16]:
np.transpose(A)

array([[0.61940231, 0.27532383, 0.88168087],
       [0.21969051, 0.062626  , 0.57197644],
       [0.74993031, 0.50449268, 0.30733518]])