# Prueba de conocimiento


Problemas: 1

- Crear variables de tipo entero, punto flotante, string (cadena de texto) e imprimir sus tipos.
- Crear una lista con múltiplos de 5, comenzando en 0 y hasta 100. **Hint: ...**
- Usar los primeros 5 elementos de la lista anterior para imprimir esa cantidad de veces la letra 'A'. Ejemplo: De [0, 5, 10, ...], para 5, sería imprimir 'AAAAA'.
- Crear una matriz con números aleatorios usando numpy y trasponer la matriz.

In [45]:
a = 5 
b = 9.18
c = 'str'
print (type(a))
print (type(b))
print (type(c))

<class 'int'>
<class 'float'>
<class 'str'>


In [46]:
lista = list(range(0,101,5))
print (lista)
print (type(lista))

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]
<class 'list'>


In [47]:
for n in range (0,101,5):
    print (n)
print (type(n))

0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95
100
<class 'int'>


In [48]:
first_f = lista [:5]
print (first_f)
print (type(first_f))

[0, 5, 10, 15, 20]
<class 'list'>


In [49]:
for n in first_f :
    print (n*'A')


AAAAA
AAAAAAAAAA
AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA


In [50]:
import numpy as np 

B = np.random.random((3,3,3,)) #agregar un tercer argumento "n" a la lista, generara "n" cantidad de veces esa matriz  
                               
print (B)

[[[0.81243609 0.16976066 0.877518  ]
  [0.02628646 0.91571371 0.94653394]
  [0.04777975 0.16174137 0.45515249]]

 [[0.14185765 0.41196423 0.52401038]
  [0.37175412 0.5502559  0.72938289]
  [0.31139182 0.21866653 0.2815223 ]]

 [[0.50854525 0.73468441 0.59931457]
  [0.85404203 0.95572942 0.52754217]
  [0.32083986 0.63409727 0.83816307]]]


In [51]:
B.T

array([[[0.81243609, 0.14185765, 0.50854525],
        [0.02628646, 0.37175412, 0.85404203],
        [0.04777975, 0.31139182, 0.32083986]],

       [[0.16976066, 0.41196423, 0.73468441],
        [0.91571371, 0.5502559 , 0.95572942],
        [0.16174137, 0.21866653, 0.63409727]],

       [[0.877518  , 0.52401038, 0.59931457],
        [0.94653394, 0.72938289, 0.52754217],
        [0.45515249, 0.2815223 , 0.83816307]]])

### Problemas 2:

1. Edad:
   - Definir una variable solicitando entrada de un entero (preguntar por la edad).
   - Asegurarse de que el tipo de dato anterior es un número entero entre 0 y 100.
   - Meter los dos puntos anteriores a una función, para sólo llamar a la función `dime_tu_edad` y que imprima un mensaje sobre la edad.
2. Listas, ciclos y numpy:
   - Generar una lista con 100 números aleatorios (`random`).
   - Guardar los valores de la lista que sean mayores que 0.7 (convertir a `np.array`).
   - Guardar en una variable `n` la longitud del vector resultante (verificar que en efeccto es un número cercano a 30).
   - Imprimir la lista de esos valores en orden inverso.
3. Escribir los primeros 100 valores de la sucesión de Fibonacci comenzando en $a_0 = 1$ y $a_1 = 1$. (`[1, 1, 2, 3, 5, 8, 13, 21, ...]`)
   - Hacer una gráfica de barras.
   

In [1]:
edad = int(input("Escribe tu edad :"))
if  edad >=100 :
    print  ("cuidate del covid abuelo.")
elif edad>0 :
    print  ("cuidate del covid principe. TQM")
else :
    print ("que tranza carnal, aun no naces, but cuidate del covid")


    

    

Escribe tu edad : 21


cuidate del covid principe. TQM


## ya me trabe en definir una funcion jaja :v 

In [24]:
def dime_tu_edad (edad):
    edad = int(input("Escribe tu edad :"))
    if edad > 100 :
        return ("cuidate del covid abuelo.")
    elif edad > 0 :
        return ("cuidate del covid principe. TQM")
    else : 
        return ("que tranza carnal, aun no naces, but cuidate del covid")
         
x = dime_tu_edad (edad)
print (x)
   

Escribe tu edad : -12020202022


que tranza carnal, aun no naces, but cuidate del covid


### Generar lista con 100 numeros aleatorios random 


In [9]:
import numpy as np
lista = list(np.random.random(100))
print (lista)

[0.4694847397130394, 0.5664151701668131, 0.6041362746565831, 0.7565991341977676, 0.6135600512039263, 0.2031633643109505, 0.8269769596825463, 0.9873791400715235, 0.08647850764423837, 0.7289194579409676, 0.7570901710147895, 0.02683750464680079, 0.8479453607689489, 0.04402240105969657, 0.3364781165153471, 0.14977962882184204, 0.5205961954729842, 0.35579173482547377, 0.8866628535116314, 0.9021201235455052, 0.08102928371224671, 0.6720670310953939, 0.33009067945470494, 0.33367310419408447, 0.7277422067508132, 0.9047739768192543, 0.7922329318633372, 0.44772883791594476, 0.29664014031586083, 0.2318258905118855, 0.8206616137169811, 0.9904435836536105, 0.5894176218489184, 0.8603664855079787, 0.4268252370890111, 0.44188691144972847, 0.23082814702392784, 0.9160687333106713, 0.9399006079183119, 0.6286925651822324, 0.3152631423522947, 0.15523065419853788, 0.036253159315584926, 0.8907350228521975, 0.49060308414153886, 0.8462406540008736, 0.16297567564367288, 0.7852668849591261, 0.6961333324767085, 0.

In [10]:
print (len(lista)) #para corroborar mi código 

100


 - Guardar los valores de la lista que sean mayores que 0.7 (convertir a `np.array`).

In [12]:
for index, n in enumerate(lista):
    print (index, n)
print (type(n))

0 0.4694847397130394
1 0.5664151701668131
2 0.6041362746565831
3 0.7565991341977676
4 0.6135600512039263
5 0.2031633643109505
6 0.8269769596825463
7 0.9873791400715235
8 0.08647850764423837
9 0.7289194579409676
10 0.7570901710147895
11 0.02683750464680079
12 0.8479453607689489
13 0.04402240105969657
14 0.3364781165153471
15 0.14977962882184204
16 0.5205961954729842
17 0.35579173482547377
18 0.8866628535116314
19 0.9021201235455052
20 0.08102928371224671
21 0.6720670310953939
22 0.33009067945470494
23 0.33367310419408447
24 0.7277422067508132
25 0.9047739768192543
26 0.7922329318633372
27 0.44772883791594476
28 0.29664014031586083
29 0.2318258905118855
30 0.8206616137169811
31 0.9904435836536105
32 0.5894176218489184
33 0.8603664855079787
34 0.4268252370890111
35 0.44188691144972847
36 0.23082814702392784
37 0.9160687333106713
38 0.9399006079183119
39 0.6286925651822324
40 0.3152631423522947
41 0.15523065419853788
42 0.036253159315584926
43 0.8907350228521975
44 0.49060308414153886
45 0

In [22]:
for index, n in enumerate(lista):
    if n > 0.7 :
        print (index, n)

3 0.7565991341977676
6 0.8269769596825463
7 0.9873791400715235
9 0.7289194579409676
10 0.7570901710147895
12 0.8479453607689489
18 0.8866628535116314
19 0.9021201235455052
24 0.7277422067508132
25 0.9047739768192543
26 0.7922329318633372
30 0.8206616137169811
31 0.9904435836536105
33 0.8603664855079787
37 0.9160687333106713
38 0.9399006079183119
43 0.8907350228521975
45 0.8462406540008736
47 0.7852668849591261
49 0.9237639157276877
51 0.7079396311943571
56 0.8386235639851277
57 0.97169787436891
65 0.7600202617434302
69 0.7280935762347375
71 0.7904004890275249
72 0.7084708368261646
73 0.7986785999182429
79 0.8904172200691407
81 0.9569944450799832
82 0.9853163237026438
88 0.8517992602117946
89 0.7925930364626058
92 0.9787052864527542
93 0.7708953748751488
99 0.8221561491839322


In [71]:
a, b = 0,1
for i in range(101):
    print(a, end=' ')
    a, b = b, a + b
    

0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 17711 28657 46368 75025 121393 196418 317811 514229 832040 1346269 2178309 3524578 5702887 9227465 14930352 24157817 39088169 63245986 102334155 165580141 267914296 433494437 701408733 1134903170 1836311903 2971215073 4807526976 7778742049 12586269025 20365011074 32951280099 53316291173 86267571272 139583862445 225851433717 365435296162 591286729879 956722026041 1548008755920 2504730781961 4052739537881 6557470319842 10610209857723 17167680177565 27777890035288 44945570212853 72723460248141 117669030460994 190392490709135 308061521170129 498454011879264 806515533049393 1304969544928657 2111485077978050 3416454622906707 5527939700884757 8944394323791464 14472334024676221 23416728348467685 37889062373143906 61305790721611591 99194853094755497 160500643816367088 259695496911122585 420196140727489673 679891637638612258 1100087778366101931 1779979416004714189 2880067194370816120 4660046610375530309 754011380474634642

In [72]:
print (i)

100
